# Generated by Django 3.1.3 on 2020-11-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comentario', models.DateField()),
                ('contenido_comentario', models.CharField(max_length=125)),
                ('reaccion', models.IntegerField(max_length=2)),
                ('autor_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.autor')),
                ('id_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.publicacion')),
            ],
        ),
    ]
